// <auto-generated />
using MarmaraUlasim.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarmaraUlasim.API.Migrations
{
    [DbContext(typeof(MarmaraUlasimDbContext))]
    [Migration("20261006213929_AddSeferler")]
    partial class AddSeferler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarmaraUlasim.API.Models.Durak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<double>("Boylam")
                        .HasColumnType("double precision");

                    b.Property<string>("DurakKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Enlem")
                        .HasColumnType("double precision");

                    b.Property<int?>("IlceId")
                        .HasColumnType("integer");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MahalleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IlceId");

                    b.HasIndex("MahalleId");

                    b.HasIndex("Kaynak", "DurakKodu")
                        .IsUnique();

                    b.ToTable("Duraklar");
                });

            modelBuilder.Entity("MarmaraUlasim.API.Models.Hat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("HatKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hatlar");
                });

            modelBuilder.Entity("MarmaraUlasim.API.Models.Il", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlakaKodu")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Iller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "İstanbul",
                            PlakaKodu = 34
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Edirne",
                            PlakaKodu = 22
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Kırklareli",
                            PlakaKodu = 39
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Tekirdağ",
                            PlakaKodu = 59
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Çanakkale",
                            PlakaKodu = 17
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Balıkesir",
                            PlakaKodu = 10
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Bursa",
                            PlakaKodu = 16
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Yalova",
                            PlakaKodu = 77
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Kocaeli",
                            PlakaKodu = 41
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Sakarya",
                            PlakaKodu = 54
                        },
                        new
                        {
                            Id = 11,
                            Ad = "Bilecik",
                            PlakaKodu = 11
                        });
                });

            modelBuilder.Entity("MarmaraUlasim.API.Models.Ilce", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ApiId")
                        .HasColumnType("integer");

                    b.Property<int>("IlId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiId")
                        .IsUnique();

                    b.HasIndex("IlId");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("MarmaraUlasim.API.Models.Mahalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ApiId")
                        .HasColumnType("integer");

                    b.Property<int>("IlceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApiId")
                        .IsUnique();

                    b.HasIndex("IlceId");

                    b.ToTable("Mahalleler");
                });

            modelBuilder.Entity("MarmaraUlasim.API.Models.Sefer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<string>("HatKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SeferKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServisKodu")
                        .HasColumnType("text");

                    b.Property<string>("VarisYonu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HatKodu");

                    b.HasIndex("Kaynak", "SeferKodu")
                        .IsUnique();

                    b.ToTable("Seferler");
                });

            modelBuilder.Entity("MarmaraUlasim.API.Models.Durak", b =>
                {
                    b.HasOne("MarmaraUlasim.API.Models.Ilce", "Ilce")
                        .WithMany()
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarmaraUlasim.API.Models.Mahalle", "Mahalle")
                        .WithMany()
                        .HasForeignKey("MahalleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ilce");

                    b.Navigation("Mahalle");
                });

            modelBuilder.Entity("MarmaraUlasim.API.Models.Ilce", b =>
                {
                    b.HasOne("MarmaraUlasim.API.Models.Il", "Il")
                        .WithMany()
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Il");
                });

            modelBuilder.Entity("MarmaraUlasim.API.Models.Mahalle", b =>
                {
                    b.HasOne("MarmaraUlasim.API.Models.Ilce", "Ilce")
                        .WithMany()
                        .HasForeignKey("IlceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ilce");
                });

            modelBuilder.Entity("MarmaraUlasim.API.Models.Sefer", b =>
                {
                    b.HasOne("MarmaraUlasim.API.Models.Hat", "Hat")
                        .WithMany()
                        .HasForeignKey("HatKodu")
                        .HasPrincipalKey("HatKodu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hat");
                });
#pragma warning restore 612, 618
        }
    }
}
