// <auto-generated />
using MarmaraUlasim.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarmaraUlasim.API.Migrations
{
    [DbContext(typeof(MarmaraUlasimDbContext))]
    [Migration("20261006163728_MarmaraUlasim")]
    partial class MarmaraUlasim
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarmaraUlasim.API.Models.Il", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlakaKodu")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Iller");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "İstanbul",
                            PlakaKodu = 34
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Edirne",
                            PlakaKodu = 22
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Kırklareli",
                            PlakaKodu = 39
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Tekirdağ",
                            PlakaKodu = 59
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Çanakkale",
                            PlakaKodu = 17
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Balıkesir",
                            PlakaKodu = 10
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Bursa",
                            PlakaKodu = 16
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Yalova",
                            PlakaKodu = 77
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Kocaeli",
                            PlakaKodu = 41
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Sakarya",
                            PlakaKodu = 54
                        },
                        new
                        {
                            Id = 11,
                            Ad = "Bilecik",
                            PlakaKodu = 11
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
